spring.application.name=Placify

#supabase database config
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update