spring.application.name=Placify

#supabase database config
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.lwfidrelmmfrutcthnoc&password=h8KnR@vY-px#L9x
spring.datasource.username=postgres
spring.datasource.password=h8KnR@vY-px#L9x
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970